title: Xpano
tagline: Automated photo stiching tool
description: |
  Automated photo stiching tool.<br>Import a directory of images and then export auto detected panoramas.
show_downloads: false
url: https://krupkat.github.io
baseurl: "/xpano"

theme: jekyll-theme-cayman

github:
  is_project_page: true
  repository_url: https://github.com/krupkat/xpano
  repository_name: xpano
  owner_name: Tomas Krupka
  owner_url: https://krupkat.cz
